#####################################################################################
#### NOTE: head over to `builds.yaml` to define what builds you'd like to run. ####
#### (i.e., datasets and subsampling schemas)  ####
#####################################################################################

#  JC altered section (point to ns3 build)
configfile:
  - spheres_profile/NS3/builds.yaml

#  JC added section (override data files)
config:
  - sequences=data/ns3_sequences.fasta
  - metadata=data/ns3_metadata.tsv
  
# Always print the commands that will be run to the screen for debugging.
printshellcmds: True

# Explain why Snakemake is running each rule.
reason: True

# Track how long each step of builds takes to rum.
stats: stats.json

# Use conda environments for augur and related binaries. This is important in a
# cluster environment where Docker is not available and Singularity may be
# prohibitively complicated to setup.
# JC altered section (disable conda for local job)
#use-conda: True

#
# Set the maximum number of cores you want Snakemake to use for this pipeline.
cores: 16

# Always print the commands that will be run to the screen for debugging.
printshellcmds: True

# JC deleted section (delete slurm config for local run) 
