configfile:
  - defaults/parameters.yaml
  - nextstrain_profiles/nextstrain/builds.yaml

cores: 8
keep-going: True
printshellcmds: True
show-failed-logs: True
reason: True
restart-times: 1
stats: stats.json
set-threads: tree=4
