name: nextstrain
channels:
- bioconda
- defaults
dependencies:
- cvxopt
- datrie
- fasttree
- iqtree
- mafft
- opencv
- pandas
- psutil
- python=3.6*
- nodejs=10
- raxml
- vcftools
- git
- pip
- pip:
  - awscli==1.18.45
  - nextstrain-augur==11.0.0
  - nextstrain-cli==2.0.0.post1
  - rethinkdb==2.3.0.post6
